serverSite/rest_framework/runtests/urls.py
"""
Blank URLConf just to keep runtests.py happy.
"""
from rest_framework.compat import patterns

urlpatterns = patterns('',
)

serverSite/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication.

The urls must be namespaced as 'rest_framework', and you should make sure
your authentication settings include `SessionAuthentication`.

    urlpatterns = patterns('',
        ...
        url(r'^auth', include('rest_framework.urls', namespace='rest_framework'))
    )
"""
from __future__ import unicode_literals
from rest_framework.compat import patterns, url


template_name = {'template_name': 'rest_framework/login.html'}

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', template_name, name='login'),
    url(r'^logout/$', 'logout', template_name, name='logout'),
)

serverSite/serverSite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^wStationMgr/', include('wStationMgr.urls', namespace="wStationMgr")),
    url(r'^wStationMgr/api/', include('rest_framework.urls', namespace='rest_framework')),    
    url(r'^wStationMgr/admin/', include(admin.site.urls)),
)

serverSite/wStationMgr/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import login
from wStationMgr import views

urlpatterns = patterns('wStationMgr.views',    
    url(r'^tree/(?P<node_id>\d+)/$', login_required( views.tree ), name='tree'),    
    url(r'^tree_json/(?P<node_id>\d+)/$', views.tree_json, name='tree_json'),    
    url(r'^help/$', views.help, name='help'),    
    url(r'^$', login_required( views.IndexView.as_view()), name='index'),
    
    # API
    url(r'^api/$', views.NodeList.as_view() ),
    url(r'^api/(?P<node_id>[0-9]+)/$', views.NodeDetail.as_view() ),
    url(r'^api/data/(?P<node_id>[0-9]+)/$', views.DataDetail.as_view() ),
    url(r'^api/data/$', views.DataList.as_view() ),
    url(r'^api/server/$', views.ServerList.as_view() ),
    url(r'^api/network/$', views.NetworkList.as_view() ),
    url(r'^api/ldevice/$', views.LogicalDeviceList.as_view() ),
    url(r'^api/lnode/$', views.LogicalNodeList.as_view() ),

    # Login / logout.
    url(r'^login/$', login),
    url(r'^logout/$', views.logout_page, name='logout_page'),    
)

serverSite/wStationMgr/forms.py
from django.forms import ModelForm
from wStationMgr.models import Server,BaseTreeNode

class MyServerForm(ModelForm):
   class Meta:
      model = Server

serverSite/wStationMgr/views.py
# Create your views here.
from django.http import  Http404, HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext
from wStationMgr.models import Server, LogicalDevice, LogicalNode, BaseTreeNode, Network, Data,AttributeData,FunctionalConstraint
from wStationMgr.serializer import JSONSerializer
from wStationMgr.permissions import IsOwnerOrReadOnly

from django.core import serializers
from django.views import generic
from django.utils import timezone

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from rest_framework.renderers import JSONRenderer, XMLRenderer

from wStationMgr.serializers import BaseTreeNodeSerializer,DataSerializer,ServerSerializer,NetworkSerializer,LogicalDeviceSerializer,LogicalNodeSerializer
from django.contrib.auth import logout
from django.template import Context, Template
import json


class IndexView(generic.ListView):
    template_name = 'wStationMgr/index.html'
    context_object_name = 'root_list'
	
    def get_queryset(self):
        """Return the last five created servers."""
        return BaseTreeNode.objects.filter( 
		parent__isnull=True, active = True
	).order_by('-created_date')
		
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
	context['user'] = self.request.user
        return context

class DetailView(generic.DetailView):
    model = Server
    template_name = 'wStationMgr/tree.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        return context 
    

class ResultsView(generic.DetailView):
    model = Server
    template_name = 'wStationMgr/results.html'



def tree(request, node_id):
    response = {'view': 'my_view', 'response_code': 0}
    try:
        root = get_object_or_404(BaseTreeNode, pk=node_id, active=True) 
	root_childs = root.get_descendants().filter( active = True );
    except (KeyError, BaseTreeNode.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'wStationMgr/tree.html', {
            'error_message': "Node does not exist.",
        })
    else:
	return render(request, 'wStationMgr/tree.html', {
            'root': root,
            'root_childs': root_childs,
            'error_message': "",
        })   


def help(request):
    return render(request, 'wStationMgr/help.html', {} )


def logout_page(request):
    """
    Log users out and re-direct them to the main page.
    """
    logout(request)
    return HttpResponseRedirect('/wStationMgr')

	
def tree_json(request, node_id):	
    response = {'view': 'my_view', 'response_code': 0}
    
    try:
        root = get_object_or_404(BaseTreeNode, pk=node_id, active=True) 
	root_childs = root.get_descendants().filter( active = True );      	
    except (KeyError, BaseTreeNode.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'wStationMgr/tree.html', {
            'error_message': "Node does not exist.",
        })
    else:
	return render(request, 'wStationMgr/tree_json.html', {
	    'root': root,
            'root_childs': root_childs,
            'error_message': "You didn't select a choice.",
        })



## Api classes ##

class NodeList(APIView):
    """
    List all nodes, or create a new snippet.
    """
    def get_object(self, node_name):
        try:
            return BaseTreeNode.objects.get(name=node_name)
        except BaseTreeNode.DoesNotExist:
            raise Http404

    def get(self, request, format=None):
	node_name = request.GET.get('name','')
	include_node = request.GET.get('includeNode','')

	if not node_name:
       		nodes = BaseTreeNode.objects.all()
	elif include_node:
		if  include_node=='true':
			nodes = self.get_object( node_name ).get_descendants( include_self = True ).filter( level__lte=1 )
		else:
			nodes = self.get_object( node_name ).get_descendants().filter( level__lte=1 )
	else:
		node = self.get_object( node_name )
		return Response ( BaseTreeNodeSerializer(node, many=False).data )

	serializer = BaseTreeNodeSerializer(nodes, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = BaseTreeNodeSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ServerList(APIView):
   
    def post(self, request, format=None):
	print request.DATA    
        serializer = ServerSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class NetworkList(APIView):
   
    def post(self, request, format=None):
	print request.DATA    
        serializer = NetworkSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class LogicalDeviceList(APIView):
   
    def post(self, request, format=None):
	print request.DATA    
        serializer = LogicalDeviceSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class LogicalNodeList(APIView):
   
    def post(self, request, format=None):
	print request.DATA    
        serializer = LogicalNodeSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class NodeDetail(APIView):

    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)
	
    """
    Retrieve, update or delete a node instance.
    """
    def get_object(self, node_id):
        try:
            return BaseTreeNode.objects.get(pk=node_id)
        except BaseTreeNode.DoesNotExist:
            raise Http404

    def get(self, request, node_id, format=None):
        node = self.get_object(node_id)
        serializer = BaseTreeNodeSerializer(node)
        return Response( serializer.data )

    def put(self, request, node_id, format=None):
        node = self.get_object(node_id)
        serializer = BaseTreeNodeSerializer(node, data=request.DATA, partial=True )
	print node.name
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, node_id, format=None):
        node = self.get_object(node_id)
        node.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)



class DataList(APIView):
    """
    List all data, or create a new snippet.
    """
    def get_object(self, data_name):
        try:
            return Data.objects.get( name=data_name )
        except Data.DoesNotExist:
            raise Http404

    def get(self, request, format=None):
	data_name = request.GET.get('name','')
	data_constraint_filter = request.GET.get('fconstraint','')

	# filter data logic
	if data_name:
       		datas = self.get_object( data_name )
		serializer = DataSerializer(datas, many=False)		
	elif data_constraint_filter:
		f_constraint_obj = get_object_or_404( FunctionalConstraint, name = data_constraint_filter )
		attr_data_set = f_constraint_obj.attr_datas
		datas = Data.objects.filter( id__in = [ attr_data.data.id for attr_data in attr_data_set.all() ] )
		serializer = DataSerializer(datas, many=True)
	else:
		datas = Data.objects.all()
		serializer = DataSerializer(datas, many=True)
	
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = DataSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class DataDetail(APIView):

    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)
        
    """
    Retrieve, update or delete a data instance.
    """
    def get_object(self, node_id):
        try:
            return Data.objects.get(pk=node_id)
        except Data.DoesNotExist:
            raise Http404

    def get(self, request, node_id, format=None):
        node = self.get_object(node_id)
        serializer = DataSerializer(node)
        return Response( serializer.data )

    def put(self, request, node_id, format=None):
        node = self.get_object(node_id)
        serializer = DataSerializer(node, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, node_id, format=None):
        node = self.get_object(node_id)
        node.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# get methods for accessing tree

serverSite/wStationMgr/templates/wStationMgr/base.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	
	<head>	    
		<link rel="stylesheet" type="text/css" href="{% static 'wStationMgr/styles.css' %}" />
		<script type="text/javascript" src="{% static 'wStationMgr/js/jquery-1.2.3.js' %}"></script>
		{% block extra_ref %}{% endblock %}
		<title>{% block title %}Work Station Manager{% endblock %}</title>

	</head>

	{% block inline_script %}{% endblock %}

	<body>
		<div id="header">			
        	{% block header %}
		<a href="{% url 'wStationMgr:index' %}"><h1> Monitor de nodos </h1></a>
	        {% endblock %}
	    </div>

	    <div id="content">
	        {% block content %}{% endblock %}
	   </div>
	   <div id="footer">
		   {% block footer %}
	   		<p> This is the footer </p>
		   {% endblock %}
	   </div>
	</body>
</html>

serverSite/wStationMgr/templates/wStationMgr/help.html
{% extends "wStationMgr/home.html" %}

{% load staticfiles %}

{% block extra_ref %}
{% endblock %}

{% block inline_script %}			
{% endblock %}	

{% block header %}
	<div class="info_section">	
		<p>	Guia de usuario.       
		</p>
	</div>
{% endblock %}

{% block content %}
	<blockquote> API </blockquote>
	<fieldset>
		<legend>Nodos</legend>
		<h4> Delete </h4>
		<p> 
		    <span> Descripcion : Borra nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" -X DELETE http://localhost:8000/wStationMgr/api/8/  </span>
		</p>
		<h4> Update </h4>
		<p> 
		    <span> Descripcion : Actualiza el titulo para nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" -X PUT -d "title=Titulo Modificado" http://localhost:8000/wStationMgr/api/8/  </span>
 	       </p>
    		<p> 
		    <span> Descripcion : Actualiza el titulo para nodo con id = 8 y login </span><br/>
		    <span> curl -H "Accept: application/json" -X PUT -d "title=Titulo Modificado XXX" -u tester:tester http://localhost:8000/wStationMgr/api/8/  </span>
	       	</p>
		<h4> Retrieve </h4>
		<p> 
    	 	    <span> Descripcion : Retorna el nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" http://localhost:8000/wStationMgr/api/8/  </span> 
		    </p>
		<p> 
    	 	    <span> Descripcion : Retorna hijos del nodo sin incluir al mismo nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" "http://localhost:8000/wStationMgr/api/?name=NASA&includeNode=false"  </span> 
		</p>
		<h4> Create </h4>
		<p> 
    	 	    <span> Descripcion : Crea un servidor asociado al nodo 1 </span><br/>
		    <span> curl -H "Accept: application/json" -X POST -d  "title=Server Auto&name=ServerWQ&description=Descripcion del servidor Auto&ip_address=168.120.36.36&os=Windows&parent=1"  http://localhost:8000/wStationMgr/api/server/  </span> 		    
        	</p>
	</fieldset>
	<br/>
	<fieldset>
		<legend>Data</legend>
		<h4> Delete </h4>
		<p> 
		    <span> Descripcion : Borra nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" -X DELETE http://localhost:8000/wStationMgr/api/8/  </span>
		</p>
		<h4> Update </h4>
		<p> 
		    <span> Descripcion : Actualiza el titulo para nodo con id = 8 </span><br/>
		    <span> curl -H "Accept: application/json" -X PUT -d "title=Titulo Modificado" http://localhost:8000/wStationMgr/api/8/  </span>
 	       </p>
    		<p> 
		    <span> Descripcion : Actualiza el titulo para nodo con id = 8 y login </span><br/>
		    <span> curl -H "Accept: application/json" -X PUT -d "title=Titulo Modificado XXX" -u tester:tester http://localhost:8000/wStationMgr/api/8/  </span>
	       	</p>
		<h4> Retrieve </h4>
		<p> 
    	 	    <span> Descripcion : Retorna data con id = 5 </span><br/>
		    <span> curl  -H "Accept: application/json" http://localhost:8000/wStationMgr/api/data/5/  </span> 
		</p>
 	        <p> 
    	 	    <span> Descripcion : Retorna data con id = 5 em formato xml </span><br/>
		    <span> curl  -H "Accept: application/xml" http://localhost:8000/wStationMgr/api/data/5/  </span> 
		    </p>
		<p> 
    	 	    <span> Descripcion : Retorna todos los datas </span><br/>
		    <span> curl -H "Accept: application/json" http://localhost:8000/wStationMgr/api/data/  </span> 
		    </p>
	    	<p> 
    	 	    <span> Descripcion : Retorna data filtrado por nombre </span><br/>
		    <span >curl  -H "Accept: application/json" http://localhost:8000/wStationMgr/api/data/?name=DN111  </span> 
		    </p>
 	        <p> 
    	 	    <span> Descripcion : Retorna los data cuyos atributo contienen restriccion = FC3 </span><br/>
		    <span> curl -H "Accept: application/json" http://localhost:8000/wStationMgr/api/data/?fconstraint=FC3  </span> 
		</p>
		<h4> Create </h4>
		<p> </p>
	</fieldset>



{% endblock %}	

serverSite/wStationMgr/templates/wStationMgr/home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    
    <link rel="stylesheet" type="text/css" href="{% static 'wStationMgr/styles.css' %}" />
    <script type="text/javascript" src="{% static 'wStationMgr/js/jquery-2.0.3.js' %}"></script>
    {% block extra_ref %}

    {% endblock %}
    
    <title> Monitor de Nodos </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'wStationMgr/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Custom CSS for the 'Heroic Features' Template -->
    <link href="{% static 'wStationMgr/css/home.css' %}" rel="stylesheet">

    {% block inline_script %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> 
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
	            	<li><a href="{% url 'admin:index' %}">admin</a></li>
			{% if user.is_authenticated %}
				<li> <a href="#"> {{ user.username }} </a> </li>
				<li> <a href="{% url 'wStationMgr:logout_page' %}"> logout </a> </li>
			{% else %}
				<li> <a href="#"> guest </a></li>
			{% endif %}			
		            	<li><a href="{% url 'wStationMgr:help' %}">help</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    
    <div class="container">

	    <div class="jumbotron hero-spacer">
   	    	    <a href="{% url 'wStationMgr:index' %}"><h1> Monitor de nodos </h1></a>
		    {% block header %}
		        <h1>A Warm Welcome!</h1>		
		    {% endblock %}		
	   </div>      
      <hr>

      <div id="content">      
      {% block content %}
      {% endblock %}
      </div>
      
      <hr>

      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Trelew Chubut 2013 </p>
          </div>
        </div>
      </footer>
      
    </div><!-- /.container -->
  
  </body>

</html>

serverSite/wStationMgr/templates/wStationMgr/index.html
{% extends "wStationMgr/home.html" %}

{% load staticfiles %}
{% load mptt_tags %}

{% block extra_ref %}	
	<script type="text/javascript" src="{% static 'wStationMgr/js/jquery-1.2.3.js' %}"></script>
{% endblock %}

{% block inline_script %}
{% endblock %}	

{% block header %}
	<div class="info_section">	
		<p>	Aqui se muestran los arboles de nodos que estan siendo monitoreadas actualmente con sus servidores asociados.</p>
	</div>
{% endblock %}

{% block content %}	
	<div id="node_content">
	{% if root_list %}
		{% include 'wStationMgr/node_content.html' %}			
        {% else %}
 	    <p>No networks are available.</p>
        {% endif %}
        </div>
				
	<div id="pager" class="pager">
		<form>
			<input type="button" value="&lt;&lt;" class="first" />
			<input type="button" value="&lt;" class="prev" />
			<input type="text" class="pagedisplay"/>
			<input type="button" value="&gt;" class="next" />
			<input type="button" value="&gt;&gt;" class="last" />
			<select class="pagesize">
				<option selected="selected"  value="10">10</option>

	
				<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
			</select>
		</form>
	</div>

	{% endblock %}	

serverSite/wStationMgr/templates/wStationMgr/node_content.html
{% load staticfiles %}
{% load mptt_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'wStationMgr/tablesorter.css' %}" />
<script type="text/javascript" src="{% static 'wStationMgr/js/jquery.tablesorter.mod.js' %}"></script>
<script type="text/javascript" src="{% static 'wStationMgr/js/jquery.tablesorter.collapsible.js' %}"></script>
<script type="text/javascript" src="{% static 'wStationMgr/js/jquery.tablesorter.pager.js' %}"></script>


<script type="text/javascript">	
	$(document).ready(
			function (){
				$(".tablesorter")
				/*
				 * td.collapsible = collapse to the first table row and show +/-
				 * td.collapsible_alt = anchor to order number
				 */
				.collapsible("td.collapsible", {
					collapse: true
				})
				.tablesorter({
				// set default sort column
				sortList: [[1,0]],
				// don't sort by first column
				headers: {0: {sorter: false}}
				// set the widgets being used - zebra stripping
				, widgets: ['zebra']
				, onRenderHeader: function (){
					this.wrapInner("<span></span>");
				}
				, debug: false
			})
			.tablesorterPager({container: $("#pager"), positionFixed: false})
				;
			}
	);
</script>


<table class="grid tablesorter" cellspacing="0" style="width: auto;">
			<colgroup>
				<col width="19" /><col width="39" /> <col width="65" /> <col width="150" /><col width="250" /><col width="150" /><col width="70" /><col width="50" /><col width="40" />
			</colgroup>
			<thead>	<tr> 
					<th style="padding: 0; margin: 0;"></th>
					<th> Nodo </th>
					<th> Tipo </th>
					<th> Titulo </th>
					<th> Descripci&oacute;n </th>
					<th> Modificado </th>
					<th> Nivel 1</th>
					<th> Total </th>
					<th> Acciones </th>
				</tr>
			</thead>
			<tbody>
				{% for root in root_list %}				
					{% if  forloop.counter|divisibleby:2 %}
						<tr>
					{% else %}
						<tr class="even">
					{% endif %}
						<td rowspan="{{ root.nodes_list.count|add:"1" }}" class="collapsible"> </td>
						<td rowspan="{{ root.nodes_list.count|add:"1" }}" class="collapsible_alt"> {{ root.name }} </td> <!-- Red -->
						<td> {{ root.get_verbose_name}} </td>
						<td> {{ root.title }} </td>
						<td> {{ root.description }} </td>
						<td> {{ root.modified_date }} </td>
						<td> {{ root.get_children.count }} </td>
						<td> {{ root.get_descendant_count }}</td>
						<td> <a href="{% url 'wStationMgr:tree' root.id %}"><img title="Ver arbol" src="{% static 'wStationMgr/images/arrow_tree.gif' %}" /></a> </td>
						</tr>
						{% if root.get_immediate_nodes %}
							{% for node in root.get_immediate_nodes %}
								{% if forloop.parentloop.counter|divisibleby:2 %}
									<tr class="expand-child">
								{% else %}
									<tr class="expand-child even">
										{% endif %}
										<td colspan="1"> <div class="bold">{{ node.get_verbose_name}}</div></td>
										<td>{{ node.name }}</td>
										<td>{{ node.description }}</td>
										<td>{{ node.modified_date }}</td>
										<td>{{ node.get_children.count }}</td>
										<td>{{ node.get_descendant_count}}</td>
										<td></td>
									</tr>
							{% endfor %}
						{% endif %}	
	        	    	{% endfor %}
			</tbody>
</table>	

serverSite/wStationMgr/templates/wStationMgr/tree.html
{% extends "wStationMgr/home.html" %}

{% load staticfiles %}
{% load mptt_tags %}

{% block extra_ref %}	
	<link type="text/css" href="{% static 'wStationMgr/css/base.css' %}" rel="stylesheet" />
	<link type="text/css" href="{% static 'wStationMgr/css/spacetree.css' %}" rel="stylesheet" />
	<script type="text/javascript" src="{% static 'wStationMgr/js/Jit/jit.js' %}"></script>
	<script type="text/javascript" src="{% static 'wStationMgr/js/tree.js' %}"></script>
{% endblock %}

{% block inline_script %}
	<script type="text/javascript">

 	$(function() {
			$( "#toogle" ).click(function( e ) {
				e.preventDefault();
				$( "#node_details" ).toggle( "slow", function() { // add callback for once the toggle has occured
        				if ( !$('#node_details').is(":hidden") ) { // is the div showing?
					    $("#toogle img").attr("src", "{% static 'wStationMgr/images/arrow-up-icon.png' %}");				
				        } else { // is the div hidden?
					    $("#toogle img").attr("src", "{% static 'wStationMgr/images/arrow-down-icon.png' %}");
					}
			        } );	
			});
        });


	var json =    
	{
	    id: "{{ root.id }}",   
	    name: "{{ root.name }}",   
	    data: { "type" : "{{ root.get_verbose_name }}", "immediatte_child_count" : "{{root.get_children.count}}", "total_child_count" : "{{ root.get_descendant_count}}", "is_root" : "{{ root.is_root_node }}", "is_leaf" : "{{ root.is_leaf_node }}", "data": "{{root.get_show_data }}" },   
	    children: [{% recursetree root_childs %}
	    {
        	id: "{{ node.id }}",   
	        name: "{{ node.name }}",   
		data: { "type" : "{{ node.get_verbose_name }}", "immediatte_child_count" : "{{node.get_children.count}}" , "total_child_count" : "{{ node.get_descendant_count}}","is_root" : "{{ node.is_root_node }}", "is_leaf" : "{{ node.is_leaf_node }}","data": "{{ node.get_show_data }}"},   
	        children: [{{ children }}]
	    },
	    {% endrecursetree %}]
	};
 
	var json_str = JSON.stringify( json ).replace(",]","]");
	var json = JSON.parse(json_str);

	$(function() {
	    init();
	});
	
	</script>
{% endblock %}	

{% block header %}
	<div class="info_section">	
		<p>	Se visualizan los nodos implicados en la red.       
		</p>
	</div>
{% endblock %}
{% block content %}	


<div id="container">
	<div id="log">
		<div id="log_data"></div><a href="#" id="toogle"><img src="{% static 'wStationMgr/images/arrow-down-icon.png' %}" /> </a><!--a id="click_me" href="#">Click Me</a-->
	</div>
	<div id="inner-details">
		<div id="node_details" style="display:none;"></div>
	</div>
<div id="center-container">
    <div id="infovis"></div>    
</div>
<input type="hidden" id="s-normal" name="selection" checked="checked" value="normal" />
</div>
{% endblock %}	

serverSite/wStationMgr/templates/wStationMgr/tree_json.html
{% load mptt_tags %}
{% load staticfiles %}

<script type="text/javascript" src="{% static 'wStationMgr/js/jquery-1.2.3.js' %}"></script>
<script type="text/javascript">
	var json =    
	{
	    id: "{{ root.id }}",   
	    name: "{{ root.name }}",   
	    data: { "data": "{{root.get_show_data }}" },   
	    children: [{% recursetree root_childs %}
	    {
        	id: "{{ node.id }}",   
	        name: "{{ node.name }}",   
        	data: { "data": "{{ node.get_show_data }}"},   
	        children: [{{ children }}]
	    },
	    {% endrecursetree %}]
	};
 
	var json_str = JSON.stringify( json ).replace(",]","]");
	var json = JSON.parse(json_str);	
	
	$("body").ready(function() {
		$("body").html( json_str );
	});
</script>